services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: docker_usr
      POSTGRES_PASSWORD: docker_psw
      POSTGRES_DB: agents
    network_mode: host
    volumes:
      - ./docker/setup_db.sql:/docker-entrypoint-initdb.d/setup.sql

  nlw-agents-app-dev:
    build: .
    container_name: nlw-agents-app-dev
    network_mode: host
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - nlw-agents-pg
